### ISSUE TITLE
Brak w opisie funkcji TM_SetDigit()

### ISSUE THREAD

**Issue by ZbeeGin** [Antystatyczny/test#1]
Nie opisałeś co robi funkcja TM_SetDigit(), masz tylko rozpisane parametry...

**Comment by Antystatyczny** [comment]
AAA, ok. Już widzę. Zaraz to poprawię.

**Comment by ZbeeGin** [comment]
Załatwione jak widzę, więc zamykam.

**Comment by ZbeeGin** [comment]
No nie wiem. Może jednak bym to inaczej napisał...

**Comment by Antystatyczny** [comment]
No to podaj swoją wersję ;)

**Comment by ZbeeGin** [comment]
https://github.com/Antystatyczny/test/commit/9e70afbb44f011ca3af20c209f663ad3bbaac6ba#r34660598

**Comment by Antystatyczny** [comment]
Teraz jest dobrze?

**Comment by ZbeeGin** [comment]
Tak mi pasuje.

**Comment by Antystatyczny** [comment]
Ok, to zamykam.
